# Generated by Django 4.0.3 on 2022-03-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_token',
            field=models.CharField(default='error', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='did',
            field=models.CharField(default='error', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refresh_token',
            field=models.CharField(default='error', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='error', max_length=30),
        ),
    ]
