# Generated by Django 3.2.5 on 2022-03-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_userprofile_password_userprofile_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='duser',
            field=models.CharField(default='error', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='error', max_length=50),
        ),
    ]
